### ISSUE TITLE
Bump version to 0.6.0

### ISSUE THREAD

**Issue by hyww** [GoogleCloudPlatform/container-diff#166]
It seems that the latest release has an old version number.

**Comment by nkubala** [comment]
Hey @hyww, thanks for finding this. I went ahead and released [v0.6.1](https://github.com/GoogleCloudPlatform/container-diff/releases/tag/v0.6.1) since in general I don't like modifying previous releases (it can cause people's local forks to get out of sync). Go ahead and grab the latest binary from there. Sorry for the inconvenience, we'll be better about this in the future 👍
